TABLE_(LOV_TITLE)
	SERIAL_	(ID) PRIMARY_KEY
	STRING_	(NAME, 30) NOT_NULL
END_TABLE

TABLE_(LOV_CITY)
	SERIAL	(ID) PRIMARY_KEY
	STRING_	(CITY, 100) NOT_NULL
	STRING_	(DISTRICT, 100) NOT_NULL
	STRING_	(PROVINCE, 2) NOT_NULL
	STRING_	(PSC, 6)
	STRING_	(POST_OFFICE, 100)
END_TABLE

TABLE_(LOV_STREET)
	SERIAL	(ID) PRIMARY_KEY
	INT_	(CITY_ID) REFERENCES(LOV_CITY) NOT_NULL INDEX
	STRING_	(STREET, 100) NOT_NULL
	STRING	(PSC, 6) NOT_NULL
	STRING	(POST_OFFICE, 100) NOT_NULL
END_TABLE

TABLE_(LOV_SPECIES)
	SERIAL	(ID) PRIMARY_KEY
	STRING	(NAME, 100) NOT_NULL
END_TABLE

TABLE_(LOV_BREED)
	SERIAL	(ID) PRIMARY_KEY
	INT_	(LOV_SPECIES_ID) REFERENCES(LOV_SPECIES) NOT_NULL INDEX
	STRING	(NAME, 100) NOT_NULL
END_TABLE

TABLE_(LOV_SEX)
	SERIAL	(ID) PRIMARY_KEY
	STRING	(NAME, 20) NOT_NULL
END_TABLE

TABLE_(LOV_UNIT)
	SERIAL	(ID) PRIMARY_KEY
	STRING	(NAME, 20) NOT_NULL
END_TABLE

TABLE_(LOV_PRODUCT)
	SERIAL	(ID) PRIMARY_KEY
	STRING	(NAME, 100) NOT_NULL
	INT_ 	(UNIT_ID) REFERENCES(LOV_UNIT) NOT_NULL
	DOUBLE_	(PRICE) NOT_NULL
END_TABLE

TABLE_(LOV_PHRASE)
	SERIAL	(ID) PRIMARY_KEY
	STRING	(NAME, 100) NOT_NULL
	CLOB_ 	(PHRASE_TEXT)	
END_TABLE

TABLE_(CLIENT)
	SERIAL	(ID) PRIMARY_KEY
	STRING_ (FIRST_NAME, 50)
	STRING_ (LAST_NAME, 100) NOT_NULL INDEX
	INT_	(TITLE_ID) REFERENCES(LOV_TITLE)
	STRING_	(PHONE_1, 20)
	STRING_	(PHONE_2, 20)
	STRING_ (EMAIL, 100)
	INT		(CITY_ID) REFERENCES(LOV_CITY)
	INT_	(STREET_ID) REFERENCES(LOV_STREET)
	STRING_	(HOUSE_NO, 10)
	STRING_	(NOTE, 100)
	STRING_ (IC, 20)
	STRING_ (DIC, 20)
	STRING_ (ICDPH, 20)
END_TABLE

TABLE_(PATIENT)
	SERIAL  (ID) PRIMARY_KEY
	INT_ 	(CLIENT_ID) REFERENCES(CLIENT) NOT_NULL INDEX
	STRING 	(NAME, 100)
	DATE_	(BIRTH_DATE)
	INT_	(SPECIES_ID) REFERENCES (LOV_SPECIES)
	INT_	(BREED_ID) REFERENCES (LOV_BREED)
	INT_	(SEX_ID) REFERENCES (LOV_SEX)
	STRING	(NOTE, 100)
	STRING_	(LYSSET, 16)
	BOOL_	(IS_DEAD)
END_TABLE

TABLE_(RECORD)
	SERIAL 	(ID) PRIMARY_KEY
	INT_ 	(PATIENT_ID) REFERENCES(PATIENT) NOT_NULL INDEX
	TIME_	(REC_DATE)
	CLOB_ 	(DATA)
	STRING_	(INVOICE_ID, 10) INDEX
	DATE_	(PAYED)
	DATE_	(INV_DELIVERY_DATE)
	DATE_	(INV_CREATE_DATE)
	DATE_	(INV_PAYMENT_DATE)
END_TABLE

TABLE_(RECORD_ITEM)
	SERIAL	(ID) PRIMARY_KEY
	INT_ 	(RECORD_ID) REFERENCES(RECORD) NOT_NULL INDEX
	INT_	(PROD_ID) REFERENCES(LOV_PRODUCT) NOT_NULL
	DOUBLE_	(AMOUNT) NOT_NULL
	DOUBLE_	(ITEM_PRICE) NOT_NULL
	DOUBLE_	(PROD_PRICE) NOT_NULL
END_TABLE
